credentials:
    username: ""
    password: ""
accounts:
    - username: "password"
search:
    start: 0
    platrormName: "Sentinel-1"
    productType: "GRD"
    polarisationMode: "HV+HH"
    sensorOperationalMode: "EW"
    beginPosition: "[2020-01-01T00:00:00.000Z TO 2020-01-01T23:59:59.999Z]"
download:
    enable: False
    path: "snapshots"
verbose: True
